[package]
name = "goi_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12.1", default-features = false, features = [ "client", "gateway", "rustls_backend", "model" ] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4.38"